### ISSUE TITLE
Why is the Qwen2.5 output garbled and not in the training data format？

### ISSUE THREAD

**Issue by nbhhsky-hu** [MingyuJ666/Disentangling-Memory-and-Reasoning#1]
Here is an example of trained Qwen2.5
![image](https://github.com/user-attachments/assets/62862f84-969d-4ac7-8a92-fcf6ee5300d2)

**Comment by MingyuJ666** [comment]
Thank you for your question. Actually, it’s not garbled text. The garbled part refers to the reason and memory tokens. I was also puzzled by this issue at first, but later I discovered that it might be due to Qwen’s vocabulary and tokenization. This causes trainable OOV tokens to appear as garbled text, while the other parts remain normal natural language. None of the other models have this issue except for Qwen.

**Comment by nbhhsky-hu** [comment]
> Thank you for your question. Actually, it’s not garbled text. The garbled part refers to the reason and memory tokens. I was also puzzled by this issue at first, but later I discovered that it might be due to Qwen’s vocabulary and tokenization. This causes trainable OOV tokens to appear as garbled text, while the other parts remain normal natural language. None of the other models have this issue except for Qwen.

Thank you very much for your answer, it was very helpful.
